version: '3.8'

services:
  express-app:
    image: todo-express
    container_name: todo-express
    build:
      context: ./server
      dockerfile: Dockerfile

  nginx:
    image: todo-nginx
    container_name: todo-nginx
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - express-app
