version: '3.8'

services:
  react-app:
    image: todo-react-dev
    container_name: todo-react-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/workspace/client-dev
    ports:
      - 5173:5173

  express-app:
    image: todo-express-dev
    container_name: todo-express-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/workspace/server-dev
    ports:
      - 3000:3000
